# Generated by Django 3.1.4 on 2021-04-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('synopsis', models.TextField()),
                ('inclusion_criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('status', models.CharField(choices=[('S', 'Started'), ('C', 'Completed'), ('E', 'Error')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicCodeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thematic_code', models.CharField(choices=[('S', 'Social Care'), ('O', 'Obesity'), ('Di', 'Diabetes'), ('De', 'Dementia'), ('A', 'Antimicrobrial Resistance')], max_length=30)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.researchitem')),
            ],
        ),
        migrations.AddField(
            model_name='researchitem',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.researchproject'),
        ),
        migrations.CreateModel(
            name='ICD10Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_chapter_predicted', models.CharField(max_length=30)),
                ('icd10_block_predicted', models.CharField(max_length=30)),
                ('icd10_chapter', models.CharField(max_length=30)),
                ('icd10_block', models.CharField(max_length=30)),
                ('medical_terms', models.JSONField(blank=True, default=None, null=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icd10.researchitem')),
            ],
        ),
    ]
