# Generated by Django 3.1.4 on 2021-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10item',
            name='prediction_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd10item',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='project_file_url',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
