# Generated by Django 3.1.3 on 2021-05-16 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
