# Generated by Django 3.1.4 on 2021-04-18 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0002_auto_20210417_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10item',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icd10.researchitem'),
        ),
        migrations.AlterField(
            model_name='thematiccodeitem',
            name='item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icd10.researchitem'),
        ),
    ]
