# Generated by Django 3.1.3 on 2021-05-16 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0002_researchproject_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
