# Generated by Django 3.1.3 on 2021-05-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0003_auto_20210516_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.FloatField(default=0),
        ),
    ]
