# Generated by Django 3.1.4 on 2021-04-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0004_auto_20210418_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchitem',
            old_name='synopsis',
            new_name='research_summary',
        ),
    ]
