# Generated by Django 3.1.3 on 2021-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0005_auto_20210418_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10item',
            old_name='prediction_accepted',
            new_name='first_prediction_accepted',
        ),
        migrations.RemoveField(
            model_name='icd10item',
            name='icd10_block',
        ),
        migrations.RemoveField(
            model_name='icd10item',
            name='icd10_block_predicted',
        ),
        migrations.RemoveField(
            model_name='icd10item',
            name='icd10_chapter',
        ),
        migrations.RemoveField(
            model_name='icd10item',
            name='icd10_chapter_predicted',
        ),
        migrations.AddField(
            model_name='icd10item',
            name='icd10_prediction',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icd10item',
            name='icd10_validation',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
