# Generated by Django 3.1.3 on 2021-04-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd10', '0006_auto_20210424_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10item',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='researchitem',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='thematiccodeitem',
            old_name='item_id',
            new_name='item',
        ),
    ]
