import os

import torch
from datetime import date

device = torch.device("cuda:0")
MODEL = "allenai/biomed_roberta_base"
VECTORS_PATH = "{}_vectors_{}.vectors".format(MODEL, date.today())
TOP_K = 3
THRESHHOLD = 0  # Minimum number of occurences to keep the class (0 for keeping all classes)

SAMPLE_SIZE = 50
BASE_PATH = os.path.join(os.path.dirname(__file__))
FULL_DATA_PATH = BASE_PATH + "/final_data.csv"
INPUT_PATH = BASE_PATH + "/input.csv"
MODEL_PATH = BASE_PATH + "/model_svc.sav"
PCA_PATH = BASE_PATH + "/pca.sav"
NEW_MODEL_PATH = ""
PCA_COMPONENTS = 256

ROBERTA_MODEL = "distilbert-base-multilingual-cased"

labels_to_keep = ['Persons encountering health services for examination and investigation',
                  'Ischaemic heart diseases',
                  'Burns and corrosions of external body surface, specified by site',
                  'Disorders of sclera, cornea, iris and ciliary body',
                  'Malignant neoplasms of thyroid and other endocrine glands',
                  'Other viral diseases',
                  'Malignant neoplasms of digestive organs',
                  'Extrapyramidal and movement disorders',
                  'Congenital malformations and deformations of the musculoskeletal system',
                  'Neurotic, stress-related and somatoform disorders',
                  'Unspecified mental disorder',
                  'Diseases of appendix',
                  'Disorders of eyelid, lacrimal system and orbit',
                  'Disorders of skin appendages',
                  'Nutritional anaemias',
                  'Other disorders of the musculoskeletal system and connective tissue',
                  'Coagulation defects, purpura and other haemorrhagic conditions',
                  'Bacterial agents resistant to antibiotics',
                  'Other disorders of the genitourinary system',
                  'Other diseases of urinary system',
                  'Melanoma and other malignant neoplasms of skin',
                  'Noninfective enteritis and colitis',
                  'Diabetes mellitus',
                  'Bullous disorders',
                  'Malignant neoplasms of female genital organs',
                  'Other disorders of glucose regulation and pancreatic internal secretion',
                  'Persons with potential health hazards related to family and personal history and certain conditions influencing health status',
                  'Urolithiasis',
                  'Malignant neoplasms of ill-defined, secondary and unspecified sites',
                  'Viral hepatitis',
                  'Drugs, medicaments and biological substances causing adverse effects in therapeutic use',
                  'Other congenital malformations',
                  'Injuries to unspecified part of trunk, limb or body region',
                  'Neoplasms of uncertain or unknown behaviour',
                  'Other dorsopathies',
                  'Malignant neoplasms of male genital organs',
                  'Schizophrenia, schizotypal and delusional disorders',
                  'Diseases of peritoneum',
                  'Diseases of middle ear and mastoid',
                  'Disorders of vitreous body and globe',
                  'Other forms of heart disease',
                  'Persons with potential health hazards related to socioeconomic and psychosocial circumstances',
                  'Delivery',
                  'Disorders of gallbladder, biliary tract and pancreas',
                  'Injuries to the wrist and hand',
                  'Intestinal infectious diseases',
                  'Disorders of muscles',
                  'Glomerular diseases',
                  'Other nutritional deficiencies',
                  'Congenital malformations of the respiratory system',
                  'Viral infections of the central nervous system',
                  'Other respiratory diseases principally affecting the interstitium',
                  'Renal tubulo-interstitial diseases',
                  'Other acute lower respiratory infections',
                  'Injuries to the elbow and forearm',
                  'Human immunodeficiency virus [HIV] disease',
                  'Other degenerative diseases of the nervous system',
                  'Other infectious diseases',
                  'Complications of surgical and medical care, not elsewhere classified',
                  'Deforming dorsopathies',
                  'Obesity and other hyperalimentation',
                  'Malignant neoplasms of eye, brain and other parts of central nervous system',
                  'Mental retardation',
                  'Malignant neoplasms of urinary tract',
                  'Other disorders originating in the perinatal period',
                  'Pulmonary heart disease and diseases of pulmonary circulation',
                  'Systemic atrophies primarily affecting the central nervous system',
                  'Behavioural and emotional disorders with onset usually occurring in childhood and adolescence',
                  'Chronic lower respiratory diseases',
                  'Congenital malformations of eye, ear, face and neck',
                  'Symptoms and signs involving the urinary system',
                  'Provisional assignment of new diseases of uncertain etiology',
                  'Benign neoplasms',
                  'Injuries to the ankle and foot',
                  'Malignant neoplasms of lip, oral cavity and pharynx',
                  'Other spirochaetal diseases',
                  'Visual disturbances and blindness',
                  'Episodic and paroxysmal disorders',
                  'Other diseases of upper respiratory tract',
                  'Other diseases of pleura',
                  'Poisoning by drugs, medicaments and biological substances',
                  'Inflammatory diseases of the central nervous system',
                  'Other bacterial diseases',
                  'Helminthiases',
                  'Malnutrition',
                  'Sequelae of injuries, of poisoning and of other consequences of external causes',
                  'Nerve, nerve root and plexus disorders',
                  'Cleft lip and cleft palate',
                  'Disorders of optic nerve and visual pathways',
                  'Diseases of oesophagus, stomach and duodenum',
                  'Other land transport accidents',
                  'Toxic effects of substances chiefly nonmedicinal as to source',
                  'Symptoms and signs involving the digestive system and abdomen',
                  'Disorders of thyroid gland',
                  'Surgical and other medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure',
                  'Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified',
                  'Injuries to the shoulder and upper arm',
                  'Persons encountering health services for specific procedures and health care',
                  'Inflammatory polyarthropathies',
                  'Spondylopathies',
                  'Congenital malformations of the urinary system',
                  'Other congenital malformations of the digestive system',
                  'Disorders of other endocrine glands',
                  'Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium',
                  'Diseases of liver',
                  'General symptoms and signs',
                  'Arthropod-borne viral fevers and viral haemorrhagic fevers',
                  'Assault',
                  'Inflammatory diseases of female pelvic organs',
                  'Cerebral palsy and other paralytic syndromes',
                  'Mycoses',
                  'Other disorders of eye and adnexa',
                  'Disorders of adult personality and behaviour',
                  'Malignant neoplasm of breast',
                  'Other diseases of blood and blood-forming organs',
                  'Abnormal findings on diagnostic imaging and in function studies, without diagnosis',
                  'Other maternal disorders predominantly related to pregnancy',
                  'Infectious arthropathies',
                  'Pedal cyclist injured in transport accident',
                  'Injuries to the thorax',
                  'Accidental poisoning by and exposure to noxious substances',
                  'Congenital malformations of genital organs',
                  'Injuries to the neck',
                  'Exposure to smoke, fire and flames',
                  'Diseases of male genital organs',
                  'Haemorrhagic and haematological disorders of fetus and newborn',
                  'Chondropathies',
                  'Injuries to the head',
                  'Other osteopathies',
                  'Renal failure',
                  'Cerebrovascular diseases',
                  'Symptoms and signs involving the circulatory and respiratory systems',
                  'Mental and behavioural disorders due to psychoactive substance use',
                  'Other and unspecified disorders of the circulatory system',
                  'Symptoms and signs involving the nervous and musculoskeletal systems',
                  'Haemolytic anaemias',
                  'Sequelae of external causes of morbidity and mortality',
                  'Conditions involving the integument and temperature regulation of fetus and newborn',
                  'Diseases of oral cavity, salivary glands and jaws',
                  'Organic, including symptomatic, mental disorders',
                  'Glaucoma',
                  'Tuberculosis',
                  'Hernia',
                  'Other and unspecified effects of external causes',
                  'Radiation-related disorders of the skin and subcutaneous tissue',
                  'Ill-defined and unknown causes of mortality',
                  'Maternal care related to the fetus and amniotic cavity and possible delivery problems',
                  'Intentional self-harm',
                  'Behavioural syndromes associated with physiological disturbances and physical factors',
                  'Noninflammatory disorders of female genital tract',
                  'Symptoms and signs involving speech and voice',
                  'Other disorders of the nervous system',
                  'Congenital malformations of the nervous system',
                  'Injuries to the knee and lower leg',
                  'Disorders of choroid and retina',
                  'Legal intervention and operations of war',
                  'Other diseases of the digestive system',
                  'Transitory endocrine and metabolic disorders specific to fetus and newborn',
                  'Viral infections characterized by skin and mucous membrane lesions',
                  'Burns and corrosions of multiple and unspecified body regions',
                  'Demyelinating diseases of the central nervous system',
                  'Respiratory and cardiovascular disorders specific to the perinatal period',
                  'Abnormal findings on examination of blood, without diagnosis',
                  'Acute upper respiratory infections',
                  'Arthrosis',
                  'Protozoal diseases',
                  'Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery',
                  'Disorders of breast',
                  'Infections specific to the perinatal period',
                  'Complications of labour and delivery',
                  'Chromosomal abnormalities, not elsewhere classified',
                  'Aplastic and other anaemias',
                  'Congenital malformations of the circulatory system',
                  'Malignant neoplasms of respiratory and intrathoracic organs',
                  'Symptoms and signs involving cognition, perception, emotional state and behaviour',
                  'Systemic connective tissue disorders',
                  'Injuries involving multiple body regions',
                  'Complications predominantly related to the puerperium',
                  'Injuries to the abdomen, lower back, lumbar spine and pelvis',
                  'Other joint disorders',
                  'Diseases of myoneural junction and muscle',
                  'Urticaria and erythema',
                  'Disorders of psychological development',
                  'Infections of the skin and subcutaneous tissue',
                  'Digestive system disorders of fetus and newborn',
                  'Diseases of arteries, arterioles and capillaries',
                  'Malignant neoplasms of mesothelial and soft tissue',
                  'Other diseases of intestines',
                  'Suppurative and necrotic conditions of lower respiratory tract',
                  'Disorders of lens',
                  'Papulosquamous disorders',
                  'Disorders related to length of gestation and fetal growth',
                  'Lung diseases due to external agents',
                  'Other disorders of the skin and subcutaneous tissue',
                  'Symptoms and signs involving the skin and subcutaneous tissue',
                  'Mood [affective] disorders',
                  'Other diseases of the respiratory system',
                  'Injuries to the hip and thigh',
                  'Effects of foreign body entering through natural orifice',
                  'Diseases of inner ear',
                  'Influenza and pneumonia',
                  'Malignant neoplasms of bone and articular cartilage',
                  'Persons with potential health hazards related to communicable diseases',
                  'Other disorders of kidney and ureter',
                  'Other soft tissue disorders',
                  'Polyneuropathies and other disorders of the peripheral nervous system',
                  'Metabolic disorders',
                  'Other disorders of ear',
                  'Disorders of ocular muscles, binocular movement, accommodation and refraction',
                  'Dermatitis and eczema',
                  'Certain disorders involving the immune mechanism',
                  'Sequelae of infectious and parasitic diseases',
                  'Pregnancy with abortive outcome',
                  'Disorders of conjunctiva',
                  'Persons encountering health services in circumstances related to reproduction',
                  'Malignant neoplasms, stated or presumed to be primary, of lymphoid, haematopoietic and related tissue',
                  'Infections with a predominantly sexual mode of transmission',
                  'Certain early complications of trauma',
                  'In situ neoplasms',
                  'Disorders of bone density and structure',
                  'Persons encountering health services in other circumstances',
                  'Falls',
                  'Bacterial, viral and other infectious agents',
                  'Hypertensive diseases']
