on:
  push:
    branches:
      - devops
      - develop
      - master

name: Project Deployment

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy to Elasticbeanstalk
      id: eb-deploy
      run: |
        cd client
        npm install @angular/cli
        npm run build
        cp -r dist/PFA-Frontend ../server/PFA-Frontend
        cd ../server
        pip install awsebcli
        cd server/
        eb list
        eb labs cleanup-versions --older-than 10 --force
        eb deploy medical-extraction-env

